const { Schema, model } = require("mongoose");

const ProductSchema = new Schema({
  code: Number,
  url: String,
  product_name: String,
  generic_name: String,
  quantity: String,
  brands: String,
  brands_tags: String,
  categories: String,
  categories_tags: String,
  categories_en: String,
  labels: String,
  labels_tags: String,
  labels_en: String,
  stores: String,
  countries: String,
  countries_tags: String,
  countries_en: String,
  cities_tags: String,
  ingredients_text: String,
  ingredients_tags: String,
  ingredients_analysis_tags: String,
  allergens: String,
  additives_n: Number,
  nutriscore_score: Number,
  nutriscore_grade: String,
  pnns_groups_1: String,
  pnns_groups_2: String,
  food_groups: String,
  food_groups_tags: String,
  food_groups_en: String,
  states: String,
  states_tags: String,
  states_en: String,
  ecoscore_score: String,
  ecoscore_grade: String,
  nutrient_levels_tags: String,
  product_quantity: Number,
  completeness: Number,
  last_image_t: Number,
  main_category: String,
  main_category_en: String,
  image_url: String,
  image_small_url: String,
  image_nutrition_url: String,
  image_nutrition_small_url: String,
  energy_100g: Number,
  fat_100g: Number,
  saturated_fat_100g: Number,
  carbohydrates_100g: Number,
  sugars_100g: Number,
  fiber_100g: Number,
  proteins_100g: Number,
  salt_100g: Number,
  sodium_100g: Number,
  nutrition_score_fr_100g: Number,
});

module.exports = model("Product", ProductSchema);
